package com.hoopladigital;

import com.hoopladigital.bean.Person;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertTrue;

/**
 * test ONLY to satisfy coverage numbers (testing autogenerated code)
 */
public class PersonTest {
    @Test
    public void coverageTest() {
        Person george = makeGeorge();
        Person james = makeJames();
        assertFalse(james.equals(null));
        assertTrue(james.equals(james));
        assertFalse(james.equals(george));
        assertEquals(james.toString(), james.toString());
        assertNotEquals(0, james.hashCode());
    }

    private Person makeJames() {
        Person james = new Person();
        james.setFirstName("James");
        james.setMiddleName("Knox");
        james.setLastName("Polk");
        return james;
    }

    private Person makeGeorge() {
        Person george = new Person();
        george.setId(1L);
        george.setFirstName("George");
        george.setLastName("Washington");
        return george;
    }
}
