package com.hoopladigital.test;

import com.hoopladigital.bean.Pet;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertTrue;

/**
 * test ONLY to satisfy coverage numbers (testing autogenerated code)
 */
public class PetTest {

    @Test
    public void coverageTest() {
        Pet dog = makeDog(1L);
        Pet cat = makeCat(1L);
        assertFalse(dog.equals(null));
        assertTrue(dog.equals(dog));
        assertFalse(dog.equals(cat));
        assertEquals(dog.toString(), dog.toString());
        assertNotEquals(0, dog.hashCode());
    }
    private Pet makeDog(long personId) {
        Pet dog = new Pet();
        dog.setName("Dog");
        dog.setPersonId(personId);
        return dog;
    }

    private Pet makeCat(long personId) {
        Pet cat = new Pet();
        cat.setName("Cat");
        cat.setPersonId(personId);
        return cat;
    }
}
